// Auto-generated API functions for calculator plugin
// Generated by refresh_frontend_apis.py
// Do not edit this file manually - it will be overwritten

const API_URL = window._env_?.REACT_APP_API_URL || "http://localhost:8000";

/**
 * Calculator Plugin API Functions
 * Auto-generated from backend implementation
 */

/**
 * Get calculator information
 */
export const calculatorInfo = async () => {
  try {
    const url = `${API_URL}/calculator/`
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling calculatorInfo:', error);
    throw error;
  }
};

/**
 * Perform a calculation
 */
export const calculate = async (request) => {
  try {
    const url = `${API_URL}/calculator/calculate`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling calculate:', error);
    throw error;
  }
};


// Default export with all functions
export default {
calculatorInfo, calculate
};
