// Auto-generated API functions for reportgenerator plugin
// Generated by refresh_frontend_apis.py
// Do not edit this file manually - it will be overwritten

const API_URL = window._env_?.REACT_APP_API_URL || "http://localhost:8000";

/**
 * Reportgenerator Plugin API Functions
 * Auto-generated from backend implementation
 */

/**
 * Get report generator information
 */
export const reportgeneratorInfo = async () => {
  try {
    const url = `${API_URL}/reportgenerator/`
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling reportgeneratorInfo:', error);
    throw error;
  }
};

/**
 * Validate database and tables exist
 */
export const validateData = async (request) => {
  try {
    const url = `${API_URL}/reportgenerator/check-data`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling validateData:', error);
    throw error;
  }
};

/**
 * Get available monitor IDs from the database
 */
export const listMonitorIds = async (request) => {
  try {
    const url = `${API_URL}/reportgenerator/monitor-ids`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling listMonitorIds:', error);
    throw error;
  }
};

/**
 * Get power plant meter data
 */
export const getPowerPlantData = async (request) => {
  try {
    const url = `${API_URL}/reportgenerator/power-plant-data`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling getPowerPlantData:', error);
    throw error;
  }
};

/**
 * Get PV tap position data
 */
export const getTapValueData = async (request) => {
  try {
    const url = `${API_URL}/reportgenerator/tap-value-data`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling getTapValueData:', error);
    throw error;
  }
};

/**
 * Generate complete PDF report from power monitoring data
 */
export const createReport = async (request) => {
  try {
    const url = `${API_URL}/reportgenerator/generate-report`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling createReport:', error);
    throw error;
  }
};


// Default export with all functions
export default {
reportgeneratorInfo, validateData, listMonitorIds, getPowerPlantData, getTapValueData, createReport
};
