// Auto-generated API functions for nodecheck plugin
// Generated by refresh_frontend_apis.py
// Do not edit this file manually - it will be overwritten

const API_URL = window._env_?.REACT_APP_API_URL || "http://localhost:8000";

/**
 * Nodecheck Plugin API Functions
 * Auto-generated from backend implementation
 */

/**
 * Get nodecheck information
 */
export const nodecheckInfo = async () => {
  try {
    const url = `${API_URL}/nodecheck/`
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling nodecheckInfo:', error);
    throw error;
  }
};

/**
 * Get comprehensive node status
 */
export const getNodeStatus = async (request) => {
  try {
    const url = `${API_URL}/nodecheck/status`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling getNodeStatus:', error);
    throw error;
  }
};

/**
 * Get running processes information
 */
export const getProcessesEndpoint = async (request) => {
  try {
    const url = `${API_URL}/nodecheck/processes`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling getProcessesEndpoint:', error);
    throw error;
  }
};

/**
 * Get network connections information
 */
export const getConnectionsEndpoint = async (request) => {
  try {
    const url = `${API_URL}/nodecheck/connections`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling getConnectionsEndpoint:', error);
    throw error;
  }
};

/**
 * Run all available checks and return comprehensive results
 */
export const runAllChecksEndpoint = async (request) => {
  try {
    const url = `${API_URL}/nodecheck/run-all-checks`
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request)
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `HTTP error! status: ${response.status}`);
    }
    return await response.json();
  } catch (error) {
    console.error('Error calling runAllChecksEndpoint:', error);
    throw error;
  }
};


// Default export with all functions
export default {
nodecheckInfo, getNodeStatus, getProcessesEndpoint, getConnectionsEndpoint, runAllChecksEndpoint
};
