FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir "egauge-python[all]" confluent-kafka crcmod intelhex
COPY egauge_kafka_producer.py .
CMD ["python", "-u", "egauge_kafka_producer.py"]
